#!/usr/bin/env bash

prj_root=`dirname $(realpath "$0")`/..
tgt_dir=$prj_root/target
rel_dir=$tgt_dir/release
rel_bin_dir=$rel_dir/bin
dbg_dir=$tgt_dir/debug
dbg_bin_dir=$tgt_dir/debug/bin

life_dir=$prj_root
life_exe=$rel_bin_dir/multithreaded_life
life_dbg=$dbg_bin_dir/multithreaded_life

# blinker
# args=" -s 3 -c 10 -g 1 -i 000111"
# glider & blinker
args=" -s 10 -c 10 -g 4 -i 010000000000100011101110000000"

# build
echo "Building life binaries..."
echo ""
cd $life_dir
make PRETTY=true DBG=true multi || { x=$? printf "failed while building, bailing...\n\n\n"; exit $x; }
echo "Executing multi w/ args '$args'..."
echo ""
$life_dbg $args || { x=$? printf "failed while executing '$args', bailing...\n\n\n"; exit $x; }
echo ""
echo "done."
echo ""
echo ""
